### ISSUE TITLE
Refactor project structure to be more generic Ionic project

### ISSUE THREAD

**Issue by villebro** [tikki-fi/tikki-app#7]
Change the project structure and documentation to comply with official guide: https://ionicframework.com/docs/intro/tutorial/project-structure/
Also evaluate if the two separate `npm` install steps could be combined (perhaps making the root directory dependencies development dependencies), moving the `package.json` and `package-lock.json` files from `www` down to the root directory.

**Comment by IlmariKu** [comment]
Will work on this.
